import type { Metadata } from "next";

import "./globals.css";
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import BackgroundSliderTailwind from '../components/BackgroundSliderTailwind';

const inter = Inter({
  subsets: ['latin'],
  // Define a CSS variable name for use in Tailwind
  variable: '--font-inter', 
  display: 'swap', // Ensures text is visible while font loads
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
       <body>
        <Navbar />
        
        <main className="container mx-0 px-0 py-0 mt-0">
            {children}
        </main>
      </body>
    </html>
  );
}
